site_name: Knowledge base
site_author: 'Zsolt Kovari'
docs_dir: docs/
repo_name: 'zkovari/knowledge-base'
repo_url: 'https://github.com/zkovari/knowledge-base'
nav:
    - Home: index.md
    - About: about.md
theme:
  name: 'material'
